`#include <numeric>` for `std::iota` (#2578)
I'm seeing CI failures in cuvs over

```
/home/coder/.conda/envs/rapids/include/raft/comms/nccl_clique.hpp(68): error: namespace "std" has no member "iota"
      std::iota(device_ids_.begin(), device_ids_.end(), 0);
```

This seems to be be cause we're using `std::iota` without including the header. Fix.

Authors:
  - Ben Frederickson (https://github.com/benfred)

Approvers:
  - Bradley Dice (https://github.com/bdice)
  - William Hicks (https://github.com/wphicks)

URL: https://github.com/rapidsai/raft/pull/2578