Add missing `<atomic>` include in `interruptible.hpp`
A future libc++ version removes transitive includes of the standard `<atomic>` header and this results in compilation errors in code using the library without an explicit inclusion.

```
raft/core/interruptible.hpp:265:8: error: no type named 'atomic_flag' in namespace 'std'
  265 |   std::atomic_flag continue_;
```