Pin to pytest 7. (#2137)
There is an unusual test failure in raft-dask:

```
Exception: ModuleNotFoundError("No module named 'raft_dask.common.comms_utils'")
```

The tests started failing at the same time that pytest 8 was released. This PR tests with `pytest==7.*` to isolate the root cause (and fix it if it is the problem).