Add missing `<atomic>` include in `interruptible.hpp` (#3060)
A future libc++ version removes transitive includes of the standard `<atomic>` header and this results in compilation errors in code using the library without an explicit inclusion.

```
raft/core/interruptible.hpp:265:8: error: no type named 'atomic_flag' in namespace 'std'
  265 |   std::atomic_flag continue_;
```

Authors:
  - Clement Courbet (https://github.com/legrosbuffle)
  - Artem M. Chirkin (https://github.com/achirkin)

Approvers:
  - Artem M. Chirkin (https://github.com/achirkin)

URL: https://github.com/rapidsai/raft/pull/3060