Add missing `#include <cassert>` in `cpp/include/raft/core/math.hpp` (#2730)
Fixes this error after https://github.com/rapidsai/raft/pull/2718 was merged:
```
raft/cpp/include/raft/core/math.hpp(85): error: identifier "assert" is undefined
    assert(false); return T{};;
    ^
```

Authors:
  - Paul Taylor (https://github.com/trxcllnt)

Approvers:
  - Divye Gala (https://github.com/divyegala)
  - MithunR (https://github.com/mythrocks)

URL: https://github.com/rapidsai/raft/pull/2730